#!/usr/bin/env python3
"""Generate src/mcq_vehicle/generated/mcqueen.{h,c} from dbc/mcqueen.dbc.

Runs cantools' C source generator and pins the timestamp line so the output is
reproducible. The firmware test suite compiles the generated code and checks
it against the hand-written gateway codec; CI runs this with --check.

    python src/mcq_vehicle/tools/gen_can_code.py          # regenerate
    python src/mcq_vehicle/tools/gen_can_code.py --check  # fail if stale
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
DBC = REPO / "src" / "mcq_vehicle" / "dbc" / "mcqueen.dbc"
OUT = REPO / "src" / "mcq_vehicle" / "generated"
STAMP = re.compile(r"generated by cantools version [^\n]*")


def render() -> dict[str, str]:
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(
            [
                sys.executable,
                "-m",
                "cantools",
                "generate_c_source",
                str(DBC),
                "--output-directory",
                tmp,
                "--database-name",
                "mcqueen",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        files = {}
        for name in ("mcqueen.h", "mcqueen.c"):
            text = (Path(tmp) / name).read_text()
            files[name] = STAMP.sub("generated by cantools from dbc/mcqueen.dbc.", text)
        return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = render()
    if args.check:
        stale = [n for n, t in files.items() if not (OUT / n).exists() or (OUT / n).read_text() != t]
        if stale:
            print(f"stale generated CAN code: {stale}; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print("generated CAN code is up to date")
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in files.items():
        (OUT / name).write_text(text)
    print(f"wrote {OUT / 'mcqueen.h'} and mcqueen.c")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
