#!/usr/bin/env python3
"""Generate test/can_vectors.h from src/mcq_vehicle/dbc/mcqueen.dbc.

The DBC is the single source of truth for frame layouts. This script encodes a
fixed set of JETSON_COMMAND values with cantools, appends the CRC, and writes
them as a C header. The firmware test decodes and re-encodes every vector, so a
layout change in the DBC that is not mirrored in command.c fails the build.
Run it from the repository root; CI checks the header is up to date.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import cantools

REPO = Path(__file__).resolve().parents[3]
DBC = REPO / "src" / "mcq_vehicle" / "dbc" / "mcqueen.dbc"
HEADER = REPO / "firmware" / "gateway" / "test" / "can_vectors.h"

# steering_angle, throttle, brake, lat, long, urgent, heartbeat
VECTORS = [
    (0.0, 0.0, 0.0, 0, 0, 0, 0),
    (0.1234, 0.5, 0.0, 1, 1, 0, 4660),
    (-0.3, 0.0, 0.75, 1, 1, 0, 65535),
    (0.45, 1.0, 0.0, 1, 0, 0, 1),
    (-0.45, 0.25, 0.25, 0, 1, 1, 32768),
    (0.0001, 0.001, 0.999, 1, 1, 0, 255),
]


def crc8_j1850(data: bytes) -> int:
    crc = 0xFF
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1D) & 0xFF if crc & 0x80 else (crc << 1) & 0xFF
    return crc ^ 0xFF


def render() -> str:
    db = cantools.database.load_file(DBC)
    msg = db.get_message_by_name("JETSON_COMMAND")
    assert msg.frame_id == 0x100 and msg.length == 8
    lines = [
        "// Generated by firmware/gateway/tools/gen_can_vectors.py from",
        "// src/mcq_vehicle/dbc/mcqueen.dbc. Do not edit by hand.",
        "#ifndef GATEWAY_TEST_CAN_VECTORS_H",
        "#define GATEWAY_TEST_CAN_VECTORS_H",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "  uint8_t frame[8];",
        "  float steering_angle;",
        "  float throttle;",
        "  float brake;",
        "  int lat_enable;",
        "  int long_enable;",
        "  int request_urgent_stop;",
        "  uint16_t heartbeat;",
        "} can_vector_t;",
        "",
        "static const can_vector_t CAN_VECTORS[] = {",
    ]
    for steer, thr, brk, lat, lng, urg, hb in VECTORS:
        raw = bytearray(
            msg.encode(
                {
                    "STEERING_ANGLE": steer,
                    "THROTTLE": thr,
                    "BRAKE": brk,
                    "LAT_ENABLE": lat,
                    "LONG_ENABLE": lng,
                    "REQUEST_URGENT_STOP": urg,
                    "RESERVED": 0,
                    "HEARTBEAT": hb,
                    "CRC": 0,
                }
            )
        )
        raw[7] = crc8_j1850(bytes(raw[:7]))
        decoded = msg.decode(bytes(raw))
        assert abs(decoded["STEERING_ANGLE"] - steer) < 1e-4
        hexes = ", ".join(f"0x{b:02X}" for b in raw)
        lines.append(f"  {{{{{hexes}}}, {steer:.4f}f, {thr:.3f}f, {brk:.3f}f, {lat}, {lng}, {urg}, {hb}u}},")
    lines += [
        "};",
        "",
        "#define CAN_VECTOR_COUNT (sizeof(CAN_VECTORS) / sizeof(CAN_VECTORS[0]))",
        "",
        "#endif  // GATEWAY_TEST_CAN_VECTORS_H",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the header is stale")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not HEADER.exists() or HEADER.read_text() != text:
            print(f"{HEADER} is out of date; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print("can_vectors.h is up to date")
        return 0
    HEADER.write_text(text)
    print(f"wrote {HEADER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
