// Generated by firmware/gateway/tools/gen_can_vectors.py from
// src/mcq_vehicle/dbc/mcqueen.dbc. Do not edit by hand.
#ifndef GATEWAY_TEST_CAN_VECTORS_H
#define GATEWAY_TEST_CAN_VECTORS_H

#include <stdint.h>

typedef struct {
  uint8_t frame[8];
  float steering_angle;
  float throttle;
  float brake;
  int lat_enable;
  int long_enable;
  int request_urgent_stop;
  uint16_t heartbeat;
} can_vector_t;

static const can_vector_t CAN_VECTORS[] = {
  {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0A}, 0.0000f, 0.000f, 0.000f, 0, 0, 0, 0u},
  {{0xD2, 0x04, 0xF4, 0x01, 0x30, 0x34, 0x12, 0xFB}, 0.1234f, 0.500f, 0.000f, 1, 1, 0, 4660u},
  {{0x48, 0xF4, 0x00, 0xB8, 0x3B, 0xFF, 0xFF, 0x24}, -0.3000f, 0.000f, 0.750f, 1, 1, 0, 65535u},
  {{0x94, 0x11, 0xE8, 0x03, 0x10, 0x01, 0x00, 0xCD}, 0.4500f, 1.000f, 0.000f, 1, 0, 0, 1u},
  {{0x6C, 0xEE, 0xFA, 0xE8, 0x63, 0x00, 0x80, 0xE6}, -0.4500f, 0.250f, 0.250f, 0, 1, 1, 32768u},
  {{0x01, 0x00, 0x01, 0x9C, 0x3F, 0xFF, 0x00, 0x10}, 0.0001f, 0.001f, 0.999f, 1, 1, 0, 255u},
};

#define CAN_VECTOR_COUNT (sizeof(CAN_VECTORS) / sizeof(CAN_VECTORS[0]))

#endif  // GATEWAY_TEST_CAN_VECTORS_H
